Don't require opal-runtime, it causes error on require
When I've added this module into course-pages, node errored on
`require('asciidoctor-highlight.js')`:

TypeError: Cannot read property '$new' of undefined
    at Object.Opal.bridge (./node_modules/opal-runtime/src/opal.js:987:32)
    at Opal.klass (./node_modules/opal-runtime/src/opal.js:447:12)
    at ./node_modules/opal-runtime/src/opal.js:5299:29
    at Opal.modules.corelib/error (./node_modules/opal-runtime/src/opal.js:5415:5)
    at Object.Opal.load (./node_modules/opal-runtime/src/opal.js:2207:7)
    at Object_alloc.Opal.require [as $require] (./node_modules/opal-runtime/src/opal.js:2235:17)
    at Opal.modules.opal/base (./node_modules/opal-runtime/src/opal.js:5810:8)
    at Object.Opal.load (./node_modules/opal-runtime/src/opal.js:2207:7)
    at Object_alloc.Opal.require [as $require] (./node_modules/opal-runtime/src/opal.js:2235:17)
    at Opal.modules.opal (./node_modules/opal-runtime/src/opal.js:22165:8)